### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#1]
Wireframes outlining loose structure and layout. Solidifying the information Architecture so Dev can get rolling and we can get a good look at the content

**Comment by BurntRocket** [comment]
Here is the loose structure I put together. I am open to suggestions. The layouts are not prescriptive. 

![img_0711](https://cloud.githubusercontent.com/assets/10224417/16067512/5354b3b8-328b-11e6-8ae2-216f2072808e.JPG)

**Comment by marcusrelacion** [comment]
Going to start closing out some of these older issues.
