### ISSUE TITLE
event title isn't staying inside the div

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#104]
this is a little buggy 

<img width="1135" alt="screen shot 2016-09-25 at 4 20 07 pm" src="https://cloud.githubusercontent.com/assets/10224417/18818012/01b1d962-833c-11e6-876b-1d7b2a601c95.png">

**Comment by marcusrelacion** [comment]
fixed.

**Comment by BurntRocket** [comment]
💯
