### ISSUE TITLE
global | List style edits

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#105]
<ul>
    padding-bottom: 1.75em;

<li>
line-height: 1.75em;

<img width="1247" alt="screen shot 2016-09-25 at 4 39 27 pm" src="https://cloud.githubusercontent.com/assets/10224417/18818087/ae330344-833e-11e6-83e8-6690e6a11838.png">

**Comment by marcusrelacion** [comment]
fixed.
