### ISSUE TITLE
Add a presenter link option

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#106]
I would like to be able to link to something when you click on their photos. Would be great to be able to enter in links in this section on the cms

<img width="1100" alt="screen shot 2016-09-25 at 4 49 06 pm" src="https://cloud.githubusercontent.com/assets/10224417/18818162/2e76901a-8340-11e6-90d4-77840cb7d450.png">

<img width="837" alt="screen shot 2016-09-25 at 4 48 52 pm" src="https://cloud.githubusercontent.com/assets/10224417/18818163/311ee038-8340-11e6-93f8-8fd0df2cde62.png">

**Comment by marcusrelacion** [comment]
fixed. As an example I filled out the links for the design matters event.
