### ISSUE TITLE
Speakers | ability to change title

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#107]
I would like the ability to change the title of this section. 
It gets a little more messy than just speakers like in this example 

<img width="1230" alt="screen shot 2016-09-25 at 5 16 14 pm" src="https://cloud.githubusercontent.com/assets/10224417/18818306/e4e743b4-8343-11e6-9523-200cb382ea03.png">

**Comment by marcusrelacion** [comment]
fixed.
