### ISSUE TITLE
Gallery and Pop-UP page | Gallery opening event

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#109]
Lets get the gallery opening event back on this page

**Comment by BurntRocket** [comment]
Can we push this to the front of the list. We are about to do a promo for get out the vote and would love this to be more together

**Comment by marcusrelacion** [comment]
@BurntRocket combining issues #117 and #118 into this issue.

**Comment by marcusrelacion** [comment]
fixed.
