### ISSUE TITLE
Container on medium screen

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#111]
Want to do something crazy and adjust the container for Retina screes?
The site starts to look really nice on my laptop screen when I change the container to

.container {
    max-width: 64em !important;
}

I know it's not always the best idea to mess with the container so you tell me

**Comment by marcusrelacion** [comment]
@BurntRocket I'm not against shrinking the container, we'll have to widen it back up for anyone on a larger screen though.

**Comment by BurntRocket** [comment]
yea, we'll need to be smooth with our media queries.
