### ISSUE TITLE
Add "other Creative lunches" to those event pages

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#112]
Other Creative Lunches
PETAL at Gallery NK 
Viget 
Vox Media 
The Washington Post 
Pivot Point 
Beth Singer Design
Human Rights Campaign 
Grafik 
Blue State Digital 
Streetsense 
District Design Lab 
Gensler

**Comment by marcusrelacion** [comment]
@BurntRocket see #93. Should we limit the amount of events shown to like 2-4 and its always random creative lunch? The same could go for featured events showing other featured events. What do you think?

**Comment by BurntRocket** [comment]
yea that's def a nicer option than listing this out in text. Lemme sketch out something tomorrow

**Comment by marcusrelacion** [comment]
Sounds good 👍
