### ISSUE TITLE
Can't upload new images in siteleaf

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#114]
They're coming in blank
![screen shot 2016-09-27 at 10 08 46 am](https://cloud.githubusercontent.com/assets/10224417/18877202/7553dfb4-849a-11e6-8079-5f23967cda67.png)

**Comment by marcusrelacion** [comment]
@BurntRocket thanks to the awesome guys at siteleaf, they fixed up this issue quickly. Closing.
