### ISSUE TITLE
About Page | Email links are broken

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#115]
It looks like these are going to # 

![screen shot 2016-09-27 at 10 11 57 am](https://cloud.githubusercontent.com/assets/10224417/18877322/e86629e4-849a-11e6-9c98-b9653a9fa96c.png)

**Comment by marcusrelacion** [comment]
@BurntRocket i'll take care of this at lunch today.

**Comment by marcusrelacion** [comment]
fixed.
