### ISSUE TITLE
need the full time and time range for events

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#116]
right now the time only displays 2 digits. I need to be able to say 7:30.

**Comment by BurntRocket** [comment]
I just got in trouble with one of out partners on this one

**Comment by marcusrelacion** [comment]
@BurntRocket ill take care of it today.

**Comment by BurntRocket** [comment]
@marcusrelacion additionally. In the details section, I need to be able to be more specific on the time. For instance, on the Design Matters Event:

Doors & Exhibits: 5:30
Show: 6:30

**Comment by marcusrelacion** [comment]
@BurntRocket closing this issue to discuss further in #98
