### ISSUE TITLE
shop & Gallery | extra space on the submit a poster section

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#117]
looks like theres extra space before the text

![screen shot 2016-09-27 at 2 32 56 pm](https://cloud.githubusercontent.com/assets/10224417/18886780/66d8af80-84bf-11e6-8436-8f71a982e1da.png)

**Comment by marcusrelacion** [comment]
@BurntRocket closing this issue since it will be pushed once all the updates to the shops page are completed.
