### ISSUE TITLE
Change text links to bb-roller + increase size

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#12]
- [x]  border-bottom: 6px solid RGBA(22, 0, 250, 1);
- [x] padding-bottom: 3px; 
- [x]  font-size: 25px;
- [x]  font-family: "BBRollerMono-Headline";

![screen shot 2016-09-19 at 10 41 54 am](https://cloud.githubusercontent.com/assets/10224417/18636845/3cd50b88-7e58-11e6-96d5-b324086465b5.png)

**Comment by marcusrelacion** [comment]
@BurntRocket pushing this to post launch.

**Comment by marcusrelacion** [comment]
@BurntRocket fixed this up.
