### ISSUE TITLE
Events | Hover and Click

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#123]
I got this feedback from a few people. The event cards should only have 1 CTA(the event page) the user should be able to click anywhere on the card to go to the event page

- [x] Lets get rid of the google maps link at this level
- [x] Make the entire div clickable. 
- [x] giventhe text elements hover styles
- [x]  make the date clickable (It's funny this is the only one with a hover state but also the only one without an action)

**Comment by marcusrelacion** [comment]
@BurntRocket fixed.
