### ISSUE TITLE
Text Link | Higher Contrast 

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#124]
Lets give this a go. I usually hate the text decoration for link but think it works with this design. 

    text-decoration: underline;
    font-weight: 700;
    color: blue;

:hover
  color: black;

:visited
 color: blue 

(i.e. f you, visited links, no one cares)

<img width="1195" alt="screen shot 2016-09-28 at 10 55 29 pm" src="https://cloud.githubusercontent.com/assets/10224417/18939564/1cff7982-85cf-11e6-8a4c-a4232c1fec1b.png">

**Comment by BurntRocket** [comment]
This change only applies to text links. Ie not here and here

<img width="472" alt="screen shot 2016-09-28 at 10 59 30 pm" src="https://cloud.githubusercontent.com/assets/10224417/18939613/55462fc0-85cf-11e6-9efb-f20e1e22b4c2.png">
<img width="530" alt="screen shot 2016-09-28 at 11 00 05 pm" src="https://cloud.githubusercontent.com/assets/10224417/18939614/55484800-85cf-11e6-8eaf-b4adbe347305.png">

**Comment by marcusrelacion** [comment]
@BurntRocket fixed. Omitted the ```:visited``` color since it negated the hover state of the link and remained blue. Lmk what you think about that!
