### ISSUE TITLE
Text Shadow on event dates

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#126]
OK I GIVE IN. 

 

- [x]  ```text-shadow:1px 1px 2px rgba(0, 0, 255, 0.68);```

<img width="2121" alt="screen shot 2016-09-28 at 11 31 02 pm" src="https://cloud.githubusercontent.com/assets/10224417/18940094/a8103134-85d3-11e6-9ff4-3385f985e8a8.png">

**Comment by marcusrelacion** [comment]
@BurntRocket fixed.
