### ISSUE TITLE
Text links open in blank tabs

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#127]
want to change all the text links to open in new tabs instead of taking me out of the site.

**Comment by marcusrelacion** [comment]
@BurntRocket was doing some google searching on how to handle this, it looks like, we're going to have to use good old html inside the editor for links if you want them to open in new tabs. The only other way I've seen suggested is adding javascript:

http://stackoverflow.com/questions/3492153/markdown-open-a-new-window-link?noredirect=1&lq=1

If you decide we should use html for all the text links, just copy and paste this snippet and place it into the editor for wherever you want a link that will open in a new tab.
```<a href="#" target="_blank">Link Title</a>```

If you think we should just live with just having the links open in the same tab, thats cool too .

Going to leave this open to see what you think.

**Comment by marcusrelacion** [comment]
@BurntRocket going to close this out since we've since discussed this on slack 👍
