### ISSUE TITLE
Nav

### ISSUE THREAD

**Issue by nicegreg** [AIGAdc/DCDW#13]
Kill the home text link and make lowercase

font-size: 18px;
text-transform: none;

![screen shot 2016-09-19 at 5 43 18 pm](https://cloud.githubusercontent.com/assets/17886750/18649984/a9fa2fc6-7e90-11e6-881e-83562507574e.png)

**Comment by marcusrelacion** [comment]
fixing this in issue #9 .

**Comment by BurntRocket** [comment]
@nicegreg A thought on this. The change in type style for the menu items helps it differentiate from the text-only logo and helps it feel Special—especially on the internal pages where you don't see the logo in the full form. I think it should be all caps, smaller, and tracked out a bit. Do you feel strongly on this one?

<img width="1427" alt="screen shot 2016-09-20 at 1 30 37 pm" src="https://cloud.githubusercontent.com/assets/10224417/18681649/fe802d6a-7f36-11e6-838e-2ccf8a105f97.png">

**Comment by marcusrelacion** [comment]
@BurntRocket going to close out this issue for now.
