### ISSUE TITLE
What Comes Next...

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#130]
- [ ] I would like to include the video preview on this page. 

video here
https://vimeo.com/163727395

**Comment by marcusrelacion** [comment]
@BurntRocket do you want it to have its own section below the event text? Will there be other events that will require video?

**Comment by BurntRocket** [comment]
Lets put it below the description, above the details

**Comment by marcusrelacion** [comment]
@BurntRocket made it so that all events have the option of having a video preview (if applicable).
Check the ```has-video``` field and then paste in the video embed code into the ```embed-code``` field. Fixed.🤘🏾
