### ISSUE TITLE
shop and gallery | sponsorship link opens up a mailto

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#132]
should go to sponsors 

<img width="1385" alt="screen shot 2016-10-01 at 8 23 34 pm" src="https://cloud.githubusercontent.com/assets/10224417/19017772/13bd802e-8815-11e6-92e4-8d33d62a8cb8.png">

**Comment by marcusrelacion** [comment]
@BurntRocket let me know when you're done with content and Ill take a look!
