### ISSUE TITLE
sold out

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#133]
.sold-out {
    background-color: black;
    position: absolute;
    z-index: 100;
    bottom: 0;
    left: 0;
    right: 0;
    color: white;
    text-align: center;
    line-height: 34px;
    font-family: BBRollerMono-Headline, courier, sans-serif;
    letter-spacing: 2px;
}

I played around and got a simple solution. What may be cool is trying to get the type to work like a news ticker where the text scrolls left on repeat. 

<img width="857" alt="screen shot 2016-10-01 at 8 57 42 pm" src="https://cloud.githubusercontent.com/assets/10224417/19017868/0627e968-881a-11e6-80ef-c63c7338680d.png">

**Comment by marcusrelacion** [comment]
@BurntRocket sounds good! I'll take a stab at this!

**Comment by marcusrelacion** [comment]
https://cl.ly/252Z2F2W0L42

@BurntRocket this is ready for review. I set Creative Mornings to be "sold out" as the test to show the checkbox was working correctly. Let me know what you think.

**Comment by BurntRocket** [comment]
two small adjustments and we're set. To the text add:

    text-transform: uppercase;
    line-height: 18px;

<img width="1109" alt="screen shot 2016-10-02 at 11 14 25 am" src="https://cloud.githubusercontent.com/assets/10224417/19021514/696fb696-8891-11e6-98a9-4a818670275b.png">
