### ISSUE TITLE
Delete :after graphic everywhere + Increase h1

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#14]
It was a cool idea that won't work. Sorry

Increase h1 size to 

article h1 {
    font-size: 7.375em;
}

<img width="1444" alt="screen shot 2016-09-20 at 1 20 43 pm" src="https://cloud.githubusercontent.com/assets/10224417/18681244/3eaf0a2a-7f35-11e6-931c-74024e3d8b45.png">

**Comment by marcusrelacion** [comment]
@BurntRocket closing this issue.
