### ISSUE TITLE
2016 site—banner color

### ISSUE THREAD

**Issue by DanRader** [AIGAdc/DCDW#149]
Could we change the top banner to black. Change the font-size to 13px. Change the padding to py1. 

<img width="1414" alt="screenshot 2017-08-14 22 53 24" src="https://user-images.githubusercontent.com/10224417/29300471-8bf3e100-8143-11e7-9e4b-1a82e6abe6c1.png">

**Comment by marcusrelacion** [comment]
Updated with #166
