### ISSUE TITLE
Button Style Adjustment

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#15]
- [x] Increase font size to 18px

- [x] change padding to 
       {padding: 10px 17px;

- [x] add hover interaction
    :hover
    box-shadow: 12px 14px #111;

With a transition on the root element

- [x] add click interaction
    box-shadow: none;
    background-color: black;
    color: white;

**Comment by marcusrelacion** [comment]
@BurntRocket im going to push to post launch.

**Comment by marcusrelacion** [comment]
@BurntRocket fixed this up, I made the hover interaction consistent with the rest of the elements that have a ```:hover```.
