### ISSUE TITLE
Event Content Page | Z-Index issue

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#16]
looks like the z-index is getting screwy here
<img width="1724" alt="screen shot 2016-09-20 at 1 55 06 pm" src="https://cloud.githubusercontent.com/assets/10224417/18682353/eb0127f0-7f39-11e6-88e5-02c1015700a3.png">

**Comment by marcusrelacion** [comment]
@BurntRocket closing this issue as it's no longer overlapping the header.
