### ISSUE TITLE
Event Content Page | Header Adjusments

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#17]
- [x] increase date h2 to  
      font-size: 36px;
      line-height: 29px;

- [x]  Increase title h2 to 
      font-size: 49px;
      line-height: 56px;

- [x] decrease .event-title-header padding
       .py4 {
       padding-top: 1.4rem;
       padding-bottom: 1.4rem;
       }

- [x] Decrease adding below the time
        .mb4 {
          margin-bottom: 1rem;
         }

- [x] change the padding of the containing element to 
        margin: 10% auto 5% auto;

- [x] For SEO puposed, The Title should be the h1 on this page

- [x] Add the time to the date line

unintentional highlight in this screenshot
<img width="1659" alt="screen shot 2016-09-20 at 2 03 43 pm" src="https://cloud.githubusercontent.com/assets/10224417/18682852/cd3ebd0c-7f3b-11e6-8323-aba924c7e4dc.png">

**Comment by marcusrelacion** [comment]
@BurntRocket closing this issue since the page now reflects these changes.
