### ISSUE TITLE
Event Content Page | Body Adjustments

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#18]
- [x] Change h2 to {
    font-size: 37px;
    line-height: 48px;
    font-family: "BBRollerMono-Headline",courier,sans-serif;
}

- [x] decrease margin on the hr to 
      .article hr {
    margin: 2.5em 0;
}

- [x] Change p to {
    font-size: 21px;
    padding-bottom: 12px;
}

- [ ] Decrease the padding below the text blocks to 
    padding-bottom: 2rem;
}

- [x] Remove Price from details and change layout to be m6 and m6

- [x]  change time to "Date & Time"

- [x] Change h4s to lowercase and reduce font size

    font-size: 18px;

- [x] We'll need the ability to be flexible with the text layout above and below details. If you look at the creative lunches, they have multiple sections with h2s and content

- [ ] Is there an opacity on the logos? If we want to do that lets change oppacity ON :hover and have the resting state be full opacity. 

- [ ] Left align the become a sponsor link. Also have this link go to the sponsor list and say "See the full list"

<img width="1797" alt="screen shot 2016-09-20 at 2 37 25 pm" src="https://cloud.githubusercontent.com/assets/10224417/18684160/2906558c-7f41-11e6-9837-f367cf2335ee.png">

<img width="1784" alt="screen shot 2016-09-20 at 2 41 23 pm" src="https://cloud.githubusercontent.com/assets/10224417/18684164/2d6ef41c-7f41-11e6-88e0-58f4226826fb.png">

**Comment by marcusrelacion** [comment]
@BurntRocket closing an pushing to post launch
