### ISSUE TITLE
Homepage | Style Edits

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#19]
Overall the pacing of this page needs to be spread out. The only section where the illustration will pass through is the events but you will have more time in the white space to appreciate the illustration. 

- [x] Replace the logo with the new one. 
[LogoLockup.zip](https://github.com/AIGAdc/DCDW/files/483401/LogoLockup.zip)

- [x] Change the height to 75vh with appropriate fallbacks

- [x] Postition the logo div from the bottom not the top and increase the sizing slightly so it has more prominence. 

- [ ] Can we increase the resolution of the pattern image without suffering in speed?

- [x] Change the p to 
    font-size: 20px;
    line-height: 30px;
    font-weight: 300;

- [x] Add the white bg to the first paraghraph under DC is Design

- [x] Add a ton of space between the intro and Events I changed the margin top on .homepage-events to 999px

- [x] Delete the space under Partners and have the illustration stop scrolling in the space above partners so it doesn't bleed behind

- [x] It looks like the box with the logo in it isn't absolutely positioned inside the div containing the pattern. It should be positioned a distance from the bottom of the pattern so we dont get an overlap on to the white

**Comment by marcusrelacion** [comment]
@BurntRocket ill update the pattern post launch
