### ISSUE TITLE
Footer | Add Social Icons and styling

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#20]
Lets do something cool. 

- [x] Change

 the background to a repeat of this
![dcdw-pattern](https://cloud.githubusercontent.com/assets/10224417/18688106/de3e36c2-7f50-11e6-8d41-d89c4683a35e.jpg)

- [x] Own your made in DC statement bigger and centered

- [x] Lower the baseline of the heart

- [x] Move the website, social, and copywrite to a bottom bar

- [x] Use fontawesome for social icons. Here are the links
https://www.facebook.com/aigaDC/
https://www.instagram.com/aigadc/
https://twitter.com/aigadc
https://www.flickr.com/photos/aigadc/

- [x] Give these text links a hover of faded opacity to .8

<img width="1268" alt="screen shot 2016-09-20 at 4 44 47 pm" src="https://cloud.githubusercontent.com/assets/10224417/18688276/92e3a7ba-7f51-11e6-8b30-1a2e2fc2f2a6.png">

- [x] change the layout slightly for mobile
    Text align: center;
    padding: 18px;

<img width="380" alt="screen shot 2016-09-21 at 1 46 40 pm" src="https://cloud.githubusercontent.com/assets/10224417/18722248/282eea68-8002-11e6-9bc3-9110b23f165d.png">

**Comment by BurntRocket** [comment]
the email link on the bottom left isn't position to the left and isn't a mailto link

**Comment by BurntRocket** [comment]
above comment stands

**Comment by marcusrelacion** [comment]
@BurntRocket fixed.
