### ISSUE TITLE
Point domain name at site. 

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#22]
dcdesignweek.org

I Here are the name servers

ns-cloud-a1.googledomains.com
ns-cloud-a2.googledomains.com
ns-cloud-a3.googledomains.com
ns-cloud-a4.googledomains.com

Let me know what else you need

**Comment by marcusrelacion** [comment]
@BurntRocket might actually need you to enter in information for me since you probably have access to the google domains backend.

**Comment by BurntRocket** [comment]
do you know if I should do it in github or in Siteleaf? Don't want to F up the link between siteleaf and gh

**Comment by marcusrelacion** [comment]
Lets just hold this one on the backburner for now. From when I launched my portfolio onto gh-pages, I had to adjust settings in google domains. So lets just hold off on this one until tomorrow night.

**Comment by marcusrelacion** [comment]
@BurntRocket closing since we were able to successfully get the site up 👍
