### ISSUE TITLE
Event Content Pages | two buttons

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#25]
We're going to need the option for 2 ticket buttons for the majority of events. 

Grab your ticket (AIGA Member)
Grab your ticket (non-member)

It's not eloquent. But it's a start

We'll be able to plug in the links Wednesday night. 

<img width="1419" alt="screen shot 2016-09-20 at 10 43 49 pm" src="https://cloud.githubusercontent.com/assets/10224417/18695996/b895fc38-7f83-11e6-831a-2f46262e90a6.png">

**Comment by marcusrelacion** [comment]
@BurntRocket two button system is in place and editable, will be closing #76 as well.
