### ISSUE TITLE
Archiving the 2016 site

### ISSUE THREAD

**Issue by marcusrelacion** [AIGAdc/DCDW#33]
Once DC Design Week has concluded, we should archive the 2016 version of the site and maybe throw up a simple thank you page in its place.

@BurntRocket and @nicegreg maybe you guys want to think on what that page could potentially look like?

**Comment by BurntRocket** [comment]
If we're feeling good. We could keep the social media feed up. Maybe include a flickr feed?

The question is really, What is the value we can give after the event

**Comment by marcusrelacion** [comment]
We could provide links to the flickr feed and hashtags, so that people could dig into what occurred during this years design week in case people still come to dcdesignweek.org well past the conclusion of the events. We could also provide a link back to the AIGA DC website to point visitors to upcoming events from there as well. At least we'd be able to provide options as to just shutting the site down once its done. 

The other benefit could be to have the site placed into a ```/2016/```  or a ```/archives/2016/``` folder that could mark the beginning of having functional dcdw sites preserved as a way for visitors to look back and see how it has evolved year over year.

**Comment by BurntRocket** [comment]
We build a splash page that covers the page and it streams a slideshow of images from the flickr account

then links out to flickr and other socials

and says like “we had a great time"

streams 1 photo at a time

good idea / bad idea ?

design sketch to come

**Comment by marcusrelacion** [comment]
On board 👍

**Comment by marcusrelacion** [comment]
Closing this issue now that #143 has been merged to `master`
