### ISSUE TITLE
Edits to DCDW Committee section

### ISSUE THREAD

**Issue by rrosario725** [AIGAdc/DCDW#34]
Change to this order left-right

Dan Rader   DCDW Chair
TJ Cicheki  Programming
Rica Rosario  AIGA DC President
Blake Wilton  Programming
Maeg Keane  Programming
Casey Cavanagh  Marketing & Comms
Lara
Katerina

I'll send new photos

**Comment by BurntRocket** [comment]
@marcusrelacion Can you give me two more spots in this section. The content is in there.

**Comment by marcusrelacion** [comment]
@BurntRocket just pushed this live.
