### ISSUE TITLE
Shop & Gallery

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#38]
Is this section hard coded?

Can you update with the information from the gallery opening? and link there?

<img width="1248" alt="screen shot 2016-09-22 at 3 39 56 am" src="https://cloud.githubusercontent.com/assets/10224417/18740178/5fe068f0-8076-11e6-8818-949e163ffc4b.png">

**Comment by BurntRocket** [comment]
If we can't get that done by 1. Lets comment it out and add in later

**Comment by marcusrelacion** [comment]
@BurntRocket going to comment this section out and revisit on friday. The fields for it are built, but the layout needs some tweaking.

**Comment by BurntRocket** [comment]
👍
