### ISSUE TITLE
Sponsors are too big

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#39]
They're escaping their containers! :0

<img width="1335" alt="screen shot 2016-09-22 at 3 42 44 am" src="https://cloud.githubusercontent.com/assets/10224417/18740248/c02a69d6-8076-11e6-840a-0778db99948b.png">

**Comment by BurntRocket** [comment]
this is still an issue on the shop and gallery page. 

Everywhere else looks great.

**Comment by marcusrelacion** [comment]
@BurntRocket I hard coded the sponsors on the shop and gallery page in interest of time. Closing for now and will revisit in the future to get it dynamic.
