### ISSUE TITLE
Homepage 6 highlights

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#43]
I couldn't get the correct highlights to go to the home page. 

Here are the 6 I want if you can help me. 

Design Matters
drink & draw &pizza
Design Matters
Creative Lunch: Gensler
TEDx MidAtlantic
Get out the vote gallery opening

**Comment by BurntRocket** [comment]
not seeing this one

**Comment by marcusrelacion** [comment]
@BurntRocket going to move this to post launch and will be first priority after you guys give me the green light that content is done

**Comment by BurntRocket** [comment]
@marcusrelacion can we resurrect this?

**Comment by marcusrelacion** [comment]
@BurntRocket will take a look at this sometime this weekend.

**Comment by marcusrelacion** [comment]
fixed.
