### ISSUE TITLE
Copy Edit: Comma in date on all events

### ISSUE THREAD

**Issue by rrosario725** [AIGAdc/DCDW#48]
Currently reads: Monday October, 24
Should read: Monday, October 24 (comma after day)
Applies to all events

**Comment by rrosario725** [comment]
actually the comma is in the right place on mobile, but not on desktop

**Comment by BurntRocket** [comment]
I think this got fixed in a style change 

<img width="364" alt="screen shot 2016-09-25 at 10 03 00 pm" src="https://cloud.githubusercontent.com/assets/10224417/18820466/0f987150-836c-11e6-804f-7f34a693fc1b.png">
