### ISSUE TITLE
Separation between venue name and address?

### ISSUE THREAD

**Issue by rrosario725** [AIGAdc/DCDW#49]
Anyway we can separate "ShareSpace" with "2121 14th St NW..."
Applies to all events

![screen shot 2016-09-22 at 5 18 08 am](https://cloud.githubusercontent.com/assets/22349794/18742847/4e2c9a94-8084-11e6-8b89-3c531d0d26fe.png)

**Comment by marcusrelacion** [comment]
@rrosario725 I updated this so that when you click on the venue name, it opens up a new tab with the google maps directions. The address is still visible when you click on the event though.

**Comment by BurntRocket** [comment]
I think this is a good now solution but we'll need to be able to view the address on the event page. 
Moving to done for now
