### ISSUE TITLE
Edits: Partners section on homepage

### ISSUE THREAD

**Issue by rrosario725** [AIGAdc/DCDW#54]
- [x] Change title to: Partners & Sponsors
- [x] Replace blurb with: DC Design Week is produced by AIGA DC, a volunteer-run, 501(3)c nonprofit organization, in concert with a consortium of local associations, Meetup groups and small businesses. We rely on the generosity and goodness of others to make this week of celebration a reality. Major thanks to the following partners and sponsors for your support and commitment to the DC design community. We couldn't do it without you!
- [x] Remove: &pizza
- [x] Remove: Soul & Ink
- [x] ADD: MacLab

List of partners on this page for reference only (current AIGA DC sustaining partners): 
- Aquent / Vitamin T
- Capital One
- Chief
- Deloitte Digital
- Gensler
- Goetz Printing
- MacLab

**Comment by marcusrelacion** [comment]
@BurntRocket will take a look

**Comment by rrosario725** [comment]
@marcusrelacion hey dude! would you please bump this to the top of your to do list? we need to get the homepage sponsors switched out asap, and we couldn't fix it earlier because they were hard coded. thanks so much for all your work on this. attached is the maclab logo
![maclab](https://cloud.githubusercontent.com/assets/22349794/18801086/bd528782-81ae-11e6-967e-a310e09cdbd6.png)

**Comment by marcusrelacion** [comment]
@rrosario725 hey! I'll swap this out tonight! Sorry about that!

**Comment by marcusrelacion** [comment]
@rrosario725 fixed: https://cl.ly/0Y0a2Z1z203f
