### ISSUE TITLE
Copy Edit: Sponsors Page

### ISSUE THREAD

**Issue by rrosario725** [AIGAdc/DCDW#59]
- [x] Change "AIGA DC Sustaining Sponsors" to "AIGA DC Sustaining Partners"
- [x] Change main blurb to: DC Design Week is produced by AIGA DC, a volunteer-run, 501(3)c nonprofit organization, in concert with a consortium of local associations, Meetup groups and small businesses. We rely on the generosity and goodness of others to make this week of celebration a reality. Major thanks to the following partners and sponsors for your support and commitment to the DC design community. We couldn't do it without you!
- [x] Remove "Join the List" link. Insert copy: Interested in joining the list? We'd love to hear from you. Reach out to Rica Rosario (rica@aigadc.org) to start the conversation.
- [x] ADD Chief logo

For reference only / list of AIGA DC Sustaining Partners
- Aquent / Vitamin T
- Capital One
- Chief
- Deloitte Digital
- Gensler
- Goetz Printing
- MacLab

**Comment by BurntRocket** [comment]
done
