### ISSUE TITLE
Dev Ops

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#6]
I recommend creating individual issues for this one. Including things like:
setup github to your liking.
choose a framework. 
setup siteleaf and or jekyll
etc.

**Comment by marcusrelacion** [comment]
@BurntRocket we're up and running with siteleaf as the cms, along with jekyll running under the hood. I'll be making use of basscss as the foundation of the site as well.

I'll also be continuing to clean up and document any code until I receive assets from design.
