### ISSUE TITLE
Copy Edit: Sponsors Page > Event-Specific Sponsors & In-Kind Donors

### ISSUE THREAD

**Issue by rrosario725** [AIGAdc/DCDW#61]
- [ ] Change title to: In-Kind Sponsors

- [ ] Remove: &pizza (moved to DCDW Partner Organizations)

List of peeps for reference (list only, no logo...hmmm or little logo):
- Bearded
- Dimension Creative
- Jumbie Industries
- Plum Relish
- Republic Restoratives
- Soul & Ink

**Comment by BurntRocket** [comment]
done
