### ISSUE TITLE
Copy Edit: Volunteer Page

### ISSUE THREAD

**Issue by rrosario725** [AIGAdc/DCDW#62]
Interested in lending a helping hand? Awesome! We need you. From registration and photography to preparation of materials and greeting people, there's a role for everyone. We ask that you arrive an hour before the event is scheduled to begin to help set up and connect with your fellow volunteers. At show time, you get to enjoy the presentation.

To get started, please fill out our volunteer form below!

[typeform]

**Comment by BurntRocket** [comment]
@marcusrelacion I'm having trouble adding text on this page. 
This one is low priority.

**Comment by BurntRocket** [comment]
nevermind. User error. 👊
