### ISSUE TITLE
Edits: Salon: Morgan West 

### ISSUE THREAD

**Issue by rrosario725** [AIGAdc/DCDW#63]
- [x]  Need darker image; can't read date/time
- [x]  1st line: Delete duplicate: Maybe you’ve seen the hashtag.
- [x]  Under Registration: Delete duplicate "Want to enjoy this member benefit?"

**Comment by rrosario725** [comment]
- [ ] Need darker image; can't read date/time
- [ ] 1st line: Delete duplicate: Maybe you’ve seen the hashtag.
- [ ] Under Registration: Delete duplicate "Want to enjoy this member benefit?" 
- [ ] Change "Partners" to: "Partners & Sponsors"
- [ ] Under "Partners & Sponsors" ADD: **Share Space DC** is a free community work space on 14th St. Yep, it's free. The space offers a full menu of healthy eats, refreshing drinks, free wifi, color printing and inspiration. We share space with Mulebone. Create, eat, drink, collaborate, network, play.

For a full list of DC Design Week partners and sponsors click here (http://www.dcdesignweek.org/sponsors/)

**Comment by BurntRocket** [comment]
done
