### ISSUE TITLE
Copy Edit: About Page

### ISSUE THREAD

**Issue by rrosario725** [AIGAdc/DCDW#65]
- [x]  Intro paragraph: Remove spaces before and after em dash AIGA 
- [x] DC blurb in white box, replace copy with: 

DC Design Week is led and produced by AIGA DC, the local chapter of the professional association for design. AIGA advances design as a professional craft, strategic advantage and vital cultural force. 

The DC chapter was formed in 1984, and is run by a volunteer board of directors. With over 1,230 members, AIGA DC is the fifth largest and one of the oldest chapters in the nation. We strive to cultivate, connect and celebrate the diverse work and people that make up our DC creative community.

- [x] Add Maeg Keane to Committee
- [x] Under Blake: Remove "Sponsorship" and replace with "Programming"
- [x] Update Creative Team bios and make color treat images to match Committee pics

**Comment by BurntRocket** [comment]
done
