### ISSUE TITLE
Edits: Grace Bonney Salon

### ISSUE THREAD

**Issue by rrosario725** [AIGAdc/DCDW#68]
- [x] First Paragraph, fix link: Tina Johnson [LINK to https://www.linkedin.com/in/tjmarcel], Flagship content director at Capital One.
- [x] Change: "Sign up soon! The first fifteen registrants will receive a free copy of the book." to "Sign up early! The first fifteen registrants will receive a free copy of the book."
- [x] Remove speaker section?

**Comment by BurntRocket** [comment]
done
