### ISSUE TITLE
Edits: What Comes Next Is the Future | Film Screening

### ISSUE THREAD

**Issue by rrosario725** [AIGAdc/DCDW#70]
- [x] First line: Remove comma after "Deloitte Digital"
- [x] Second paragraph: Italicize "What Comes Next Is the Future" #108 
- [x] Add (below) after the last paragraph: 

**Bearded** is user experience strategy, design, and front-end development for the multi-device web.

**Deloitte Digital** is creating a new model for a new age—we’re a creative digital consultancy. That means we bring together all the creative and technology capabilities, business acumen, and industry insight needed to help transform our clients’ businesses. With our end-to-end capabilities, clients can bring us their biggest challenges, knowing we’ve got what it takes to bring a new business vision to life with digital.

**Comment by marcusrelacion** [comment]
fixed in #108.
