### ISSUE TITLE
Copy Edits: For all creative lunches

### ISSUE THREAD

**Issue by rrosario725** [AIGAdc/DCDW#72]
Change copy from: "Lunch is included. Registration is $10, limited to 50 attendees and is open to AIGA members first!" to "Lunch is included. Registration is $10, limited to 50 attendees."
- [ ] Remove "and is open to AIGA members first!"
- [ ] Add period after "attendees"
- [ ] NOTE: The number of attendees is different for each lunch. Please DO NOT change the number. Thanks!

After each respective "Lunch is included. Registration is $10, limited to ### attendees. " blurb per event, ADD copy below: 

Priority registration for AIGA members opens at noon on October 4th. General registration opens at noon on October 6th. Grab a spot at the beginning of the registration line, and [sign up to become a member today!](http://www.aiga.org/join)

**Comment by BurntRocket** [comment]
done
