### ISSUE TITLE
Edits: Dev & Design: Harmony in the Digital Space

### ISSUE THREAD

**Issue by rrosario725** [AIGAdc/DCDW#73]
- [x] Fix list spacing after 2nd paragraph (edit asked in #105 )
- [x] Add hyperlink: As a part of [DCFemTech’s October Tour De Code](http://dcfemtech.github.io/tourdecode) and a partnership between DCFemTech, Women Who Code, and AIGA.
- [x] Add "DC" after AIGA in last line after list: As a part of [DCFemTech’s October Tour De Code](http://dcfemtech.github.io/tourdecode) and a partnership between DCFemTech, Women Who Code, and AIGA DC.

**Comment by marcusrelacion** [comment]
@rrosario725 Fixed in #105.
