### ISSUE TITLE
Switch out the featured events

### ISSUE THREAD

**Issue by rrosario725** [AIGAdc/DCDW#75]
Can we use these as the featured events, pretty please?

[TEDx MidAtlantic](http://www.dcdesignweek.org/events/tedx-and-tedx-afterparty.html)
[Dev & Design: Harmony in the Digital Space](http://www.dcdesignweek.org/events/dev-and-design.html)
[Salon: Morgan West, Founder of A Creative DC](http://www.dcdesignweek.org/events/salon-chat-1.html)
[Salon: Grace Bonney, Founder of Design*Sponge](http://www.dcdesignweek.org/events/tedx.html)
[Design Matters: Live with Debbie Millman featuring Abbott Miller](http://www.dcdesignweek.org/events/design-matters.html)
[Creative Mornings DC | Linn Meyers](http://www.dcdesignweek.org/events/creative-mornings.html)

**Comment by marcusrelacion** [comment]
Currently working on this, its not playing right. Will update if I find a solution.

**Comment by rrosario725** [comment]
duplicate issue  / dan already did one / closing this now
