### ISSUE TITLE
SEO Optimization — Get us up on the Search results

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#77]

**Comment by marcusrelacion** [comment]
This looks promising:
https://github.com/jekyll/jekyll-seo-tag

**Comment by marcusrelacion** [comment]
@BurntRocket implemented jekyll-seo-tag and is working nicely right now, will continue to leave this issue open.

**Comment by BurntRocket** [comment]
![screen shot 2016-09-30 at 11 22 36 am](https://cloud.githubusercontent.com/assets/10224417/18996914/40386f62-8700-11e6-8621-82cd2e73be41.png)

The title is reading wrong. 

Should say DC Design Week 2016

Is this something on our end?
