### ISSUE TITLE
broken link on gallery page

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#79]
![screen shot 2016-09-22 at 1 09 43 pm](https://cloud.githubusercontent.com/assets/10224417/18758422/0909ae2e-80c6-11e6-92d4-93881814211d.png)

This link isn't working. Should go to https://www.aiga.org/get-out-the-vote/

**Comment by marcusrelacion** [comment]
@BurntRocket got it

**Comment by marcusrelacion** [comment]
@BurntRocket live!
