### ISSUE TITLE
Developer Delivery

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#8]
Prep files for delivery. 
Capture any animations. Prep any assets, fonts, icons, etc.

**Comment by nicegreg** [comment]
Can we dump photos that relate to the landing page here @BurntRocket

Photos should be clean and relate to the content as closely as possible.

**Comment by BurntRocket** [comment]
Use any photo from here https://www.flickr.com/photos/aigadc/albums there are a few photos labeled DCDW '15. If you need to go stock, Start with UnSplash. feel free to drop photos that have the right vibe then we'll find the right photos
