### ISSUE TITLE
Remove white background from Favicon

### ISSUE THREAD

**Issue by marcusrelacion** [AIGAdc/DCDW#88]

**Comment by BurntRocket** [comment]
whats weird is that it looks fine when you view the source code. 
![screen shot 2016-09-23 at 3 24 59 pm](https://cloud.githubusercontent.com/assets/10224417/18798750/fc4c35d0-81a1-11e6-9eae-0fe6ae3780f6.png)

**Comment by marcusrelacion** [comment]
@BurntRocket that is weird.

**Comment by BurntRocket** [comment]
I fixed this one. Does that mean I get paid extra?

**Comment by BurntRocket** [comment]
<img width="252" alt="screen shot 2016-09-25 at 9 09 27 pm" src="https://cloud.githubusercontent.com/assets/10224417/18819753/6319baa8-8364-11e6-8911-90c506888b4a.png">
