### ISSUE TITLE
Nav adjustments

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#9]
- [x] Kill Home (people can click on the icon)
- [x] Kill the container around the nav items
- [x] Change the menu items to
    font-size: 13px;
    letter-spacing: 2px;
- [ ] We need a hover and active state for these guys. 
you could do something like...
background-color: blue;
    padding: 7px 14px;
    color: white;

And just :hover {
color: blue;
}

- [x] Change the height to 
.py3 {
    padding-top: 1.5rem;
    padding-bottom: 1.5rem;
}
- [x] kill the drop shadow
- [ ] move the padding to the root element instead of the pseudo. Right now we're getting a jump on hover

<img width="1440" alt="screen shot 2016-09-15 at 7 58 27 pm" src="https://cloud.githubusercontent.com/assets/10224417/18571274/1154d92e-7b7f-11e6-9cbf-fed558627d09.png">

**Comment by BurntRocket** [comment]
We need a hover and active state for these guys. 

you could do something like...
background-color: blue;
    padding: 7px 14px;
    color: white;

And just :hover {
color: blue;
}

<img width="1440" alt="screen shot 2016-09-15 at 8 06 27 pm" src="https://cloud.githubusercontent.com/assets/10224417/18571393/0bc653d8-7b80-11e6-8901-cc1da5a0aff3.png">

**Comment by BurntRocket** [comment]
Two more. 
Change the height to 

.py3 {
    padding-top: 1.5rem;
    padding-bottom: 1.5rem;
}

and kill the drop shadow

**Comment by BurntRocket** [comment]
I unchecked the hover/active state box. @marcusrelacion 

The flood background is for active page.
For events, lets count event subpages as in "EVENTS"

The hover should be the change in color value only

**Comment by marcusrelacion** [comment]
@BurntRocket moving to post launch
