### ISSUE TITLE
AAUIW: Visual Cue for Sold Out Events

### ISSUE THREAD

**Issue by marcusrelacion** [AIGAdc/DCDW#92]
@BurntRocket what do you think of introducing a checkbox for sold out events in the CMS, that will possibly add a banner or an icon that indicates the event is sold out?

**Comment by BurntRocket** [comment]
love it. lets think about the visual solution for this guy

**Comment by marcusrelacion** [comment]
@BurntRocket closing this issue as the discussion has moved to #133.
