### ISSUE TITLE
Creative lunch Logos

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#95]
I would like to be able to add logos and images to the body. OR just be able to include a logo for just creative lunches like so. 

<img width="937" alt="screen shot 2016-09-25 at 12 21 03 pm" src="https://cloud.githubusercontent.com/assets/10224417/18816569/89542d60-831a-11e6-8484-2fd801c57b9a.png">

**Comment by marcusrelacion** [comment]
fixed.

**Comment by BurntRocket** [comment]
I'm getting negative feedback on this change. Can we roll this one back? People are saying the would rather see it in a sponsors section at the bottom

**Comment by marcusrelacion** [comment]
@BurntRocket I'll take a look at this tonight.
