### ISSUE TITLE
Enable mark down in the speakers section

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#96]
I would like to able to use text links in these presenter descriptions. Right now it looks like its plain text. 

<img width="642" alt="screen shot 2016-09-25 at 12 44 59 pm" src="https://cloud.githubusercontent.com/assets/10224417/18816769/ee9a593a-831d-11e6-9089-df44bc36f0db.png">

**Comment by marcusrelacion** [comment]
@BurntRocket fixed in #125
