### ISSUE TITLE
Speaker Bio Style adjustments

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#97]
Change the body type to:
 
   font-size: 1.2rem;
    line-height: 1.6em;

change the space below the h6 to .mb2 {
    margin-bottom: .6rem;

<img width="1073" alt="screen shot 2016-09-25 at 12 58 13 pm" src="https://cloud.githubusercontent.com/assets/10224417/18816845/bd2dd91a-831f-11e6-88ca-428b5af546b4.png">

**Comment by marcusrelacion** [comment]
@BurntRocket fixed.
