### ISSUE TITLE
Events pages | Details adjustments

### ISSUE THREAD

**Issue by BurntRocket** [AIGAdc/DCDW#98]
I went threw and deleted a bunch of the padding bottom attributes. I think this just needs to feel more concise so the user wants to get down through all the details. The Design Matters event is the best example. 

<img width="1366" alt="screen shot 2016-09-25 at 1 00 28 pm" src="https://cloud.githubusercontent.com/assets/10224417/18816873/7d588168-8320-11e6-929c-dbd001296b6f.png">

- [x] right now the date & time and venue labels are styled differently 
please style both to be 
    font-size: 18px;
    font-weight: 800;

<img width="829" alt="screen shot 2016-09-25 at 1 05 11 pm" src="https://cloud.githubusercontent.com/assets/10224417/18816898/ef84c30a-8320-11e6-99e1-31971694bdfd.png">

It would be great to have the day of week, date, and time to be broken on their own lines

- [x] Can we have a field for adding in the address? This will be important for the day of the event. People may pull up the website to make sure they're in the right place

**Comment by marcusrelacion** [comment]
- [ ] "@marcusrelacion additionally. In the details section, I need to be able to be more specific on the time. For instance, on the Design Matters Event:

Doors & Exhibits: 5:30
Show: 6:30"

Comment copied over from #116

**Comment by marcusrelacion** [comment]
@BurntRocket https://cl.ly/2y393z3f3U24

fixed. The fields for "doors-open" and "event-start" need to be populated for all the events currently listed. Once they're filled in with content, they'll appear in the details section.

**Comment by marcusrelacion** [comment]
``

**Comment by BurntRocket** [comment]
this looks awesome! Can I make a style tweak to the extra doors+show texts?

    font-size: 15px;
    font-weight: 700;
    color: #5a5a5a;
    margin-bottom: 0;

<img width="491" alt="screen shot 2016-09-28 at 4 31 49 pm" src="https://cloud.githubusercontent.com/assets/10224417/18931250/5dcec08e-8599-11e6-8e88-6b38ab41dbb7.png">

**Comment by marcusrelacion** [comment]
@BurntRocket thoughts?
https://cl.ly/060P1q3W3o0t

**Comment by marcusrelacion** [comment]
fixed.

**Comment by BurntRocket** [comment]
Sorry. one last adjustment. I think we went a little overboard on the icons. 
It actually looks cleaner without. 

Lets also reduce the margin-bottom to .1rem

If you are feeling like it really needs the icon love to break up the text, I would suggest doing it in the titles instead...but I think I'm ok with the typography heavy deal

**Comment by BurntRocket** [comment]
<img width="1353" alt="screen shot 2016-09-28 at 10 40 31 pm" src="https://cloud.githubusercontent.com/assets/10224417/18939273/09e21f46-85cd-11e6-8910-5439fc49a16d.png">

**Comment by marcusrelacion** [comment]
@BurntRocket fixed
